#!/bin/bash

app_name=$(basename "$(pwd)")

[ -f docker-compose.yml ] || $SHELL docker-compose.yml.sh >docker-compose.yml
[ -f Dockerfile ] || $SHELL Dockerfile.sh >Dockerfile

[ docker-compose.yml.sh -nt docker-compose.yml ] && \
  echo '[WARN] The docker-compose template was updated'
[ Dockerfile.sh -nt Dockerfile ] && \
  echo '[WARN] The Dockerfile template was updated'

docker-compose run --rm web npm install
